"""Add School Model in database and link user to it

Revision ID: 0810153fc3e3
Revises: 2f4521008b5b
Create Date: 2021-01-15 15:01:12.688791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0810153fc3e3'
down_revision = '2f4521008b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('head', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('head')
    )
    op.create_index(op.f('ix_school_id'), 'school', ['id'], unique=False)
    op.create_index(op.f('ix_school_name'), 'school', ['name'], unique=True)
    op.add_column('user', sa.Column('school', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_school'), 'user', ['school'], unique=False)
    op.create_foreign_key(None, 'user', 'school', ['school'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_school'), table_name='user')
    op.drop_column('user', 'school')
    op.drop_index(op.f('ix_school_name'), table_name='school')
    op.drop_index(op.f('ix_school_id'), table_name='school')
    op.drop_table('school')
    # ### end Alembic commands ###
