"""Rename user school_id foreign key

Revision ID: 138d9d60edf8
Revises: eca9a685530f
Create Date: 2021-03-12 17:44:10.287382

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '138d9d60edf8'
down_revision = 'eca9a685530f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.alter_column('user', 'school', new_column_name='school_id', existing_type=sa.types.Integer)
    op.create_foreign_key(None, 'user', 'school', ['school_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.alter_column('user', 'school_id', new_column_name='school', existing_type=sa.types.Integer)
    op.create_foreign_key(None, 'user', 'school', ['school'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
