"""Update file model

Revision ID: 2e583c3937d1
Revises: c32be91965c2
Create Date: 2021-07-02 16:44:35.995542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e583c3937d1'
down_revision = 'c32be91965c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_type', sa.String(length=10), nullable=False))
    op.add_column('files', sa.Column('submission_id', sa.String(length=36), nullable=True))
    op.add_column('files', sa.Column('marks', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'files', 'files', ['submission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'marks')
    op.drop_column('files', 'submission_id')
    op.drop_column('files', 'file_type')
    # ### end Alembic commands ###
