"""Link Division and Student

Revision ID: 42f206c339df
Revises: 8769c70e44a7
Create Date: 2021-04-24 15:12:50.006079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f206c339df'
down_revision = '8769c70e44a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentdivisions',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('division_id', sa.String(length=36), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'division_id')
    )
    op.create_index(op.f('ix_studentdivisions_batch_number'), 'studentdivisions', ['batch_number'], unique=False)
    op.add_column('divisions', sa.Column('number_of_batches', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_divisions_number_of_batches'), 'divisions', ['number_of_batches'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_divisions_number_of_batches'), table_name='divisions')
    op.drop_column('divisions', 'number_of_batches')
    op.drop_index(op.f('ix_studentdivisions_batch_number'), table_name='studentdivisions')
    op.drop_table('studentdivisions')
    # ### end Alembic commands ###
