"""Add School Model in database

Revision ID: 4b09d0a1149f
Revises: 2f4521008b5b
Create Date: 2021-01-15 10:25:38.727050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b09d0a1149f'
down_revision = '2f4521008b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('head', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('head')
    )
    op.create_index(op.f('ix_school_id'), 'school', ['id'], unique=False)
    op.create_index(op.f('ix_school_name'), 'school', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_name'), table_name='school')
    op.drop_index(op.f('ix_school_id'), table_name='school')
    op.drop_table('school')
    # ### end Alembic commands ###
