"""Add description to file

Revision ID: 5034f9c72f24
Revises: 2e583c3937d1
Create Date: 2021-07-02 23:17:23.376396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5034f9c72f24'
down_revision = '2e583c3937d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'description')
    # ### end Alembic commands ###
