"""Add name field to Year model

Revision ID: 6c38bfd37c53
Revises: 7b2f235b8ffe
Create Date: 2021-03-07 17:15:48.838635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c38bfd37c53'
down_revision = '7b2f235b8ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('year', sa.Column('name', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_year_name'), 'year', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_year_name'), table_name='year')
    op.drop_column('year', 'name')
    # ### end Alembic commands ###
