"""Add in new stuff

Revision ID: 712896d43a93
Revises: 42f206c339df
Create Date: 2021-06-27 15:45:56.363371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712896d43a93'
down_revision = '42f206c339df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeslots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_time', 'end_time', 'school_id', name='unique_start_end_school_timeslot')
    )
    op.create_index(op.f('ix_timeslots_school_id'), 'timeslots', ['school_id'], unique=False)
    op.create_table('lectures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.String(length=9), nullable=False),
    sa.Column('time_slot_id', sa.String(length=36), nullable=False),
    sa.Column('division_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=9), nullable=False),
    sa.Column('room_number', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['timeslots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectures_division_id'), 'lectures', ['division_id'], unique=False)
    op.create_index(op.f('ix_lectures_id'), 'lectures', ['id'], unique=False)
    op.create_index(op.f('ix_lectures_time_slot_id'), 'lectures', ['time_slot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lectures_time_slot_id'), table_name='lectures')
    op.drop_index(op.f('ix_lectures_id'), table_name='lectures')
    op.drop_index(op.f('ix_lectures_division_id'), table_name='lectures')
    op.drop_table('lectures')
    op.drop_index(op.f('ix_timeslots_school_id'), table_name='timeslots')
    op.drop_table('timeslots')
    # ### end Alembic commands ###
