"""Added year models

Revision ID: 7b2f235b8ffe
Revises: bc055fd38dce
Create Date: 2021-02-11 16:50:42.242689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2f235b8ffe'
down_revision = 'bc055fd38dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_year_end_year'), 'year', ['end_year'], unique=False)
    op.create_index(op.f('ix_year_id'), 'year', ['id'], unique=False)
    op.create_index(op.f('ix_year_school_id'), 'year', ['school_id'], unique=False)
    op.create_index(op.f('ix_year_start_year'), 'year', ['start_year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_year_start_year'), table_name='year')
    op.drop_index(op.f('ix_year_school_id'), table_name='year')
    op.drop_index(op.f('ix_year_id'), table_name='year')
    op.drop_index(op.f('ix_year_end_year'), table_name='year')
    op.drop_table('year')
    # ### end Alembic commands ###
