"""Initial revision

Revision ID: 8769c70e44a7
Revises: 
Create Date: 2021-04-11 17:01:51.271414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8769c70e44a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('head', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_head'), 'school', ['head'], unique=True)
    op.create_index(op.f('ix_school_id'), 'school', ['id'], unique=False)
    op.create_index(op.f('ix_school_name'), 'school', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('profile_picture', sa.String(length=41), nullable=True),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('type', postgresql.ENUM('superuser', 'student', 'professor', 'admin', name='user_type'), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_school_id'), 'user', ['school_id'], unique=False)
    op.create_table('year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'school_id', 'start_year', 'end_year')
    )
    op.create_index(op.f('ix_year_end_year'), 'year', ['end_year'], unique=False)
    op.create_index(op.f('ix_year_id'), 'year', ['id'], unique=False)
    op.create_index(op.f('ix_year_name'), 'year', ['name'], unique=False)
    op.create_index(op.f('ix_year_school_id'), 'year', ['school_id'], unique=False)
    op.create_index(op.f('ix_year_start_year'), 'year', ['start_year'], unique=False)
    op.create_table('admin',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_admin_user_id'), 'admin', ['user_id'], unique=False)
    op.create_table('professor',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_professor_user_id'), 'professor', ['user_id'], unique=False)
    op.create_table('term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('current_year_term', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('has_electives', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['year_id'], ['year.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_term_end_date'), 'term', ['end_date'], unique=False)
    op.create_index(op.f('ix_term_id'), 'term', ['id'], unique=False)
    op.create_index(op.f('ix_term_name'), 'term', ['name'], unique=False)
    op.create_index(op.f('ix_term_start_date'), 'term', ['start_date'], unique=False)
    op.create_index(op.f('ix_term_year_id'), 'term', ['year_id'], unique=False)
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('elective_code', sa.String(length=20), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'course_code', 'term_id', name='_unique_by_name_code_term')
    )
    op.create_index(op.f('ix_course_course_code'), 'course', ['course_code'], unique=False)
    op.create_index(op.f('ix_course_elective_code'), 'course', ['elective_code'], unique=False)
    op.create_index(op.f('ix_course_id'), 'course', ['id'], unique=False)
    op.create_index(op.f('ix_course_name'), 'course', ['name'], unique=False)
    op.create_index(op.f('ix_course_term_id'), 'course', ['term_id'], unique=False)
    op.create_table('student',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_student_term_id'), 'student', ['term_id'], unique=False)
    op.create_index(op.f('ix_student_user_id'), 'student', ['user_id'], unique=False)
    op.create_table('division',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('division_code', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'division_code', name='_unique_by_course_division')
    )
    op.create_index(op.f('ix_division_course_id'), 'division', ['course_id'], unique=False)
    op.create_index(op.f('ix_division_division_code'), 'division', ['division_code'], unique=False)
    op.create_index(op.f('ix_division_id'), 'division', ['id'], unique=False)
    op.create_index(op.f('ix_division_professor_id'), 'division', ['professor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_division_professor_id'), table_name='division')
    op.drop_index(op.f('ix_division_id'), table_name='division')
    op.drop_index(op.f('ix_division_division_code'), table_name='division')
    op.drop_index(op.f('ix_division_course_id'), table_name='division')
    op.drop_table('division')
    op.drop_index(op.f('ix_student_user_id'), table_name='student')
    op.drop_index(op.f('ix_student_term_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_course_term_id'), table_name='course')
    op.drop_index(op.f('ix_course_name'), table_name='course')
    op.drop_index(op.f('ix_course_id'), table_name='course')
    op.drop_index(op.f('ix_course_elective_code'), table_name='course')
    op.drop_index(op.f('ix_course_course_code'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_term_year_id'), table_name='term')
    op.drop_index(op.f('ix_term_start_date'), table_name='term')
    op.drop_index(op.f('ix_term_name'), table_name='term')
    op.drop_index(op.f('ix_term_id'), table_name='term')
    op.drop_index(op.f('ix_term_end_date'), table_name='term')
    op.drop_table('term')
    op.drop_index(op.f('ix_professor_user_id'), table_name='professor')
    op.drop_table('professor')
    op.drop_index(op.f('ix_admin_user_id'), table_name='admin')
    op.drop_table('admin')
    op.drop_index(op.f('ix_year_start_year'), table_name='year')
    op.drop_index(op.f('ix_year_school_id'), table_name='year')
    op.drop_index(op.f('ix_year_name'), table_name='year')
    op.drop_index(op.f('ix_year_id'), table_name='year')
    op.drop_index(op.f('ix_year_end_year'), table_name='year')
    op.drop_table('year')
    op.drop_index(op.f('ix_user_school_id'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_school_name'), table_name='school')
    op.drop_index(op.f('ix_school_id'), table_name='school')
    op.drop_index(op.f('ix_school_head'), table_name='school')
    op.drop_table('school')
    # ### end Alembic commands ###
