"""Update profile_picture length

Revision ID: 8f1dfe37f875
Revises: 0810153fc3e3
Create Date: 2021-01-29 19:03:47.079339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f1dfe37f875'
down_revision = '0810153fc3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_picture',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_picture',
               existing_type=sa.String(length=36),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###
