"""Update Course model with panel and elective code

Revision ID: 9f4b569fbad6
Revises: 55c144d0952f
Create Date: 2021-03-24 12:44:22.988585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f4b569fbad6'
down_revision = '55c144d0952f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course_code', sa.String(length=20), nullable=False))
    op.add_column('course', sa.Column('elective_code', sa.String(length=20), nullable=True))
    op.add_column('course', sa.Column('panel_code', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_course_course_code'), 'course', ['course_code'], unique=False)
    op.create_index(op.f('ix_course_elective_code'), 'course', ['elective_code'], unique=False)
    op.create_index(op.f('ix_course_panel_code'), 'course', ['panel_code'], unique=False)
    op.drop_constraint('_unique_by_name_code_term', 'course', type_='unique')
    op.create_unique_constraint('_unique_by_name_code_term', 'course', ['name', 'course_code', 'panel_code', 'term_id'])
    op.drop_index('ix_course_code', table_name='course')
    op.drop_column('course', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False))
    op.create_index('ix_course_code', 'course', ['code'], unique=False)
    op.drop_constraint('_unique_by_name_code_term', 'course', type_='unique')
    op.create_unique_constraint('_unique_by_name_code_term', 'course', ['name', 'code', 'term_id'])
    op.drop_index(op.f('ix_course_panel_code'), table_name='course')
    op.drop_index(op.f('ix_course_elective_code'), table_name='course')
    op.drop_index(op.f('ix_course_course_code'), table_name='course')
    op.drop_column('course', 'panel_code')
    op.drop_column('course', 'elective_code')
    op.drop_column('course', 'course_code')
    # ### end Alembic commands ###
