"""Make school head non-nullable

Revision ID: bc055fd38dce
Revises: 8f1dfe37f875
Create Date: 2021-02-10 21:55:41.354666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc055fd38dce'
down_revision = '8f1dfe37f875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('head', table_name='school')
    op.alter_column('school', 'head',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.create_index(op.f('ix_school_head'), 'school', ['head'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_head'), table_name='school')
    op.alter_column('school', 'head',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.create_index('head', 'school', ['head'], unique=True)
    # ### end Alembic commands ###
