"""added term model

Revision ID: f0d919cf23f6
Revises: 7b2f235b8ffe
Create Date: 2021-02-12 18:14:45.543917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d919cf23f6'
down_revision = '7b2f235b8ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('current_year_term', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('has_electives', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['year_id'], ['year.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_term_end_date'), 'term', ['end_date'], unique=False)
    op.create_index(op.f('ix_term_id'), 'term', ['id'], unique=False)
    op.create_index(op.f('ix_term_name'), 'term', ['name'], unique=False)
    op.create_index(op.f('ix_term_year_id'), 'term', ['year_id'], unique=False)
    op.create_index(op.f('ix_term_start_date'), 'term', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_term_end_date'), table_name='term')
    op.drop_index(op.f('ix_term_id'), table_name='term')
    op.drop_index(op.f('ix_term_name'), table_name='term')
    op.drop_index(op.f('ix_term_year_id'), table_name='term')
    op.drop_index(op.f('ix_term_start_date'), table_name='term')
    op.drop_table('term')
    # ### end Alembic commands ###
